GLOBAL STATUS:
Aborted_clients.............................................. 0
Aborted_connects............................................. 28
Acl_cache_items_count........................................ 0
Binlog_cache_disk_use........................................ 11
Binlog_cache_use............................................. 68
Binlog_stmt_cache_disk_use................................... 0
Binlog_stmt_cache_use........................................ 8
Bytes_received............................................... 4099703
Bytes_sent................................................... 52151819
Caching_sha2_password_rsa_public_key......................... -----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApqwVoScqJgf0tuBfPZeE
ywtgj0ms3P4WH7sdgYuSW3A7rxdJ7lspferXE7VEAaNtQ0jo2akUBxCCIH4u7ri9
Zk830eC0pCAgSqXZenbVwB3ffi5YfsIelND2vEUkpmIuFbsYL+dxcbmqX+qbcSCF
uOb0b/ZKH5Mdok1sGtgjt8N3Mcia9TsiLTrOo5Vp8NXP2odA9e3IMcTI9zg1L1L+
Nor2g9FY+WbXtX+LoERuAwJd7QOOmt5nveMZtK9ZxGc1pGy0kjwTy7HlLe7FZvb1
XuOWnTEQMVBoZcWjml3U5FE56ZWM/GIKx0Ed+vdVOms0hyKHRN/acaRMsbTtNGKC
WwIDAQAB
-----END PUBLIC KEY-----

Com_admin_commands........................................... 159
Com_assign_to_keycache....................................... 0
Com_alter_db................................................. 0
Com_alter_event.............................................. 0
Com_alter_function........................................... 0
Com_alter_instance........................................... 0
Com_alter_procedure.......................................... 0
Com_alter_resource_group..................................... 0
Com_alter_server............................................. 0
Com_alter_table.............................................. 3
Com_alter_tablespace......................................... 0
Com_alter_user............................................... 6
Com_alter_user_default_role.................................. 0
Com_analyze.................................................. 0
Com_begin.................................................... 0
Com_binlog................................................... 0
Com_call_procedure........................................... 1
Com_change_db................................................ 62
Com_change_master............................................ 0
Com_change_repl_filter....................................... 0
Com_change_replication_source................................ 0
Com_check.................................................... 0
Com_checksum................................................. 0
Com_clone.................................................... 0
Com_commit................................................... 18
Com_create_db................................................ 3
Com_create_event............................................. 0
Com_create_function.......................................... 3
Com_create_index............................................. 0
Com_create_procedure......................................... 3
Com_create_role.............................................. 0
Com_create_server............................................ 0
Com_create_table............................................. 53
Com_create_resource_group.................................... 0
Com_create_trigger........................................... 6
Com_create_udf............................................... 0
Com_create_user.............................................. 1
Com_create_view.............................................. 7
Com_create_spatial_reference_system.......................... 0
Com_dealloc_sql.............................................. 7
Com_delete................................................... 2
Com_delete_multi............................................. 0
Com_do....................................................... 5
Com_drop_db.................................................. 2
Com_drop_event............................................... 0
Com_drop_function............................................ 0
Com_drop_index............................................... 0
Com_drop_procedure........................................... 0
Com_drop_resource_group...................................... 0
Com_drop_role................................................ 0
Com_drop_server.............................................. 0
Com_drop_spatial_reference_system............................ 0
Com_drop_table............................................... 3
Com_drop_trigger............................................. 0
Com_drop_user................................................ 0
Com_drop_view................................................ 0
Com_empty_query.............................................. 1
Com_execute_sql.............................................. 7
Com_explain_other............................................ 0
Com_flush.................................................... 2
Com_get_diagnostics.......................................... 0
Com_grant.................................................... 2
Com_grant_roles.............................................. 0
Com_ha_close................................................. 0
Com_ha_open.................................................. 0
Com_ha_read.................................................. 0
Com_help..................................................... 0
Com_import................................................... 0
Com_insert................................................... 6321
Com_insert_select............................................ 0
Com_install_component........................................ 0
Com_install_plugin........................................... 0
Com_kill..................................................... 0
Com_load..................................................... 0
Com_lock_instance............................................ 0
Com_lock_tables.............................................. 51
Com_optimize................................................. 0
Com_preload_keys............................................. 0
Com_prepare_sql.............................................. 7
Com_purge.................................................... 0
Com_purge_before_date........................................ 0
Com_release_savepoint........................................ 0
Com_rename_table............................................. 0
Com_rename_user.............................................. 0
Com_repair................................................... 0
Com_replace.................................................. 0
Com_replace_select........................................... 0
Com_reset.................................................... 0
Com_resignal................................................. 0
Com_restart.................................................. 0
Com_revoke................................................... 0
Com_revoke_all............................................... 0
Com_revoke_roles............................................. 0
Com_rollback................................................. 0
Com_rollback_to_savepoint.................................... 0
Com_savepoint................................................ 0
Com_select................................................... 427
Com_set_option............................................... 562
Com_set_password............................................. 0
Com_set_resource_group....................................... 0
Com_set_role................................................. 0
Com_signal................................................... 0
Com_show_binlog_events....................................... 0
Com_show_binlogs............................................. 0
Com_show_charsets............................................ 37
Com_show_collations.......................................... 15
Com_show_create_db........................................... 3
Com_show_create_event........................................ 0
Com_show_create_func......................................... 50
Com_show_create_proc......................................... 58
Com_show_create_table........................................ 42
Com_show_create_trigger...................................... 0
Com_show_databases........................................... 23
Com_show_engine_logs......................................... 0
Com_show_engine_mutex........................................ 0
Com_show_engine_status....................................... 0
Com_show_events.............................................. 0
Com_show_errors.............................................. 0
Com_show_fields.............................................. 186
Com_show_function_code....................................... 0
Com_show_function_status..................................... 6
Com_show_grants.............................................. 18
Com_show_keys................................................ 0
Com_show_master_status....................................... 0
Com_show_open_tables......................................... 0
Com_show_plugins............................................. 43
Com_show_privileges.......................................... 0
Com_show_procedure_code...................................... 0
Com_show_procedure_status.................................... 6
Com_show_processlist......................................... 0
Com_show_profile............................................. 0
Com_show_profiles............................................ 0
Com_show_relaylog_events..................................... 0
Com_show_replicas............................................ 0
Com_show_slave_hosts......................................... 0
Com_show_replica_status...................................... 10
Com_show_slave_status........................................ 10
Com_show_status.............................................. 2775
Com_show_storage_engines..................................... 6
Com_show_table_status........................................ 92
Com_show_tables.............................................. 49
Com_show_triggers............................................ 0
Com_show_variables........................................... 214
Com_show_warnings............................................ 46
Com_show_create_user......................................... 0
Com_shutdown................................................. 0
Com_replica_start............................................ 0
Com_slave_start.............................................. 0
Com_replica_stop............................................. 0
Com_slave_stop............................................... 0
Com_group_replication_start.................................. 0
Com_group_replication_stop................................... 0
Com_stmt_execute............................................. 7
Com_stmt_close............................................... 7
Com_stmt_fetch............................................... 0
Com_stmt_prepare............................................. 7
Com_stmt_reset............................................... 0
Com_stmt_send_long_data...................................... 0
Com_truncate................................................. 0
Com_uninstall_component...................................... 0
Com_uninstall_plugin......................................... 0
Com_unlock_instance.......................................... 0
Com_unlock_tables............................................ 51
Com_update................................................... 3
Com_update_multi............................................. 0
Com_xa_commit................................................ 0
Com_xa_end................................................... 0
Com_xa_prepare............................................... 0
Com_xa_recover............................................... 0
Com_xa_rollback.............................................. 0
Com_xa_start................................................. 0
Com_stmt_reprepare........................................... 0
Connection_errors_accept..................................... 0
Connection_errors_internal................................... 0
Connection_errors_max_connections............................ 0
Connection_errors_peer_address............................... 0
Connection_errors_select..................................... 0
Connection_errors_tcpwrap.................................... 0
Connections.................................................. 119
Created_tmp_disk_tables...................................... 55
Created_tmp_files............................................ 6
Created_tmp_tables........................................... 3449
Current_tls_ca............................................... ca.pem
Current_tls_capath........................................... 
Current_tls_cert............................................. server-cert.pem
Current_tls_cipher........................................... 
Current_tls_ciphersuites..................................... 
Current_tls_crl.............................................. 
Current_tls_crlpath.......................................... 
Current_tls_key.............................................. server-key.pem
Current_tls_version.......................................... TLSv1,TLSv1.1,TLSv1.2,TLSv1.3
Delayed_errors............................................... 0
Delayed_insert_threads....................................... 0
Delayed_writes............................................... 0
Error_log_buffered_bytes..................................... 2608
Error_log_buffered_events.................................... 15
Error_log_expired_events..................................... 0
Error_log_latest_write....................................... 1622930468484190
Flush_commands............................................... 3
Handler_commit............................................... 13363
Handler_delete............................................... 186
Handler_discover............................................. 0
Handler_external_lock........................................ 44477
Handler_mrr_init............................................. 0
Handler_prepare.............................................. 10862
Handler_read_first........................................... 739
Handler_read_key............................................. 20286
Handler_read_last............................................ 0
Handler_read_next............................................ 22444
Handler_read_prev............................................ 0
Handler_read_rnd............................................. 1250
Handler_read_rnd_next........................................ 2921043
Handler_rollback............................................. 0
Handler_savepoint............................................ 0
Handler_savepoint_rollback................................... 0
Handler_update............................................... 4849
Handler_write................................................ 1403577
Innodb_buffer_pool_dump_status............................... Dumping of buffer pool not started
Innodb_buffer_pool_load_status............................... Buffer pool(s) load completed at 210530 10:44:22
Innodb_buffer_pool_resize_status............................. 
Innodb_buffer_pool_pages_data................................ 256
Innodb_buffer_pool_bytes_data................................ 4194304
Innodb_buffer_pool_pages_dirty............................... 0
Innodb_buffer_pool_bytes_dirty............................... 0
Innodb_buffer_pool_pages_flushed............................. 2192
Innodb_buffer_pool_pages_free................................ 246
Innodb_buffer_pool_pages_misc................................ 10
Innodb_buffer_pool_pages_total............................... 512
Innodb_buffer_pool_read_ahead_rnd............................ 0
Innodb_buffer_pool_read_ahead................................ 45
Innodb_buffer_pool_read_ahead_evicted........................ 0
Innodb_buffer_pool_read_requests............................. 576074
Innodb_buffer_pool_reads..................................... 4652
Innodb_buffer_pool_wait_free................................. 0
Innodb_buffer_pool_write_requests............................ 272765
Innodb_data_fsyncs........................................... 2536
Innodb_data_pending_fsyncs................................... 0
Innodb_data_pending_reads.................................... 0
Innodb_data_pending_writes................................... 0
Innodb_data_read............................................. 77026304
Innodb_data_reads............................................ 4719
Innodb_data_writes........................................... 34283
Innodb_data_written.......................................... 62760960
Innodb_dblwr_pages_written................................... 1961
Innodb_dblwr_writes.......................................... 538
Innodb_log_waits............................................. 0
Innodb_log_write_requests.................................... 263006
Innodb_log_writes............................................ 31154
Innodb_os_log_fsyncs......................................... 1257
Innodb_os_log_pending_fsyncs................................. 0
Innodb_os_log_pending_writes................................. 0
Innodb_os_log_written........................................ 21318656
Innodb_page_size............................................. 16384
Innodb_pages_created......................................... 767
Innodb_pages_read............................................ 4696
Innodb_pages_written......................................... 2192
Innodb_redo_log_enabled...................................... ON
Innodb_row_lock_current_waits................................ 0
Innodb_row_lock_time......................................... 0
Innodb_row_lock_time_avg..................................... 0
Innodb_row_lock_time_max..................................... 0
Innodb_row_lock_waits........................................ 0
Innodb_rows_deleted.......................................... 0
Innodb_rows_inserted......................................... 54510
Innodb_rows_read............................................. 107085
Innodb_rows_updated.......................................... 0
Innodb_system_rows_deleted................................... 186
Innodb_system_rows_inserted.................................. 1273
Innodb_system_rows_read...................................... 31126
Innodb_system_rows_updated................................... 2116
Innodb_sampled_pages_read.................................... 0
Innodb_sampled_pages_skipped................................. 0
Innodb_num_open_files........................................ 47
Innodb_truncated_status_writes............................... 0
Innodb_undo_tablespaces_total................................ 2
Innodb_undo_tablespaces_implicit............................. 2
Innodb_undo_tablespaces_explicit............................. 0
Innodb_undo_tablespaces_active............................... 2
Key_blocks_not_flushed....................................... 0
Key_blocks_unused............................................ 6698
Key_blocks_used.............................................. 0
Key_read_requests............................................ 0
Key_reads.................................................... 0
Key_write_requests........................................... 0
Key_writes................................................... 0
Locked_connects.............................................. 0
Max_execution_time_exceeded.................................. 0
Max_execution_time_set....................................... 0
Max_execution_time_set_failed................................ 0
Max_used_connections......................................... 5
Max_used_connections_time.................................... 2021-06-04 16:41:23
Mysqlx_aborted_clients....................................... 0
Mysqlx_address............................................... ::
Mysqlx_bytes_received........................................ 0
Mysqlx_bytes_received_compressed_payload..................... 0
Mysqlx_bytes_received_uncompressed_frame..................... 0
Mysqlx_bytes_sent............................................ 0
Mysqlx_bytes_sent_compressed_payload......................... 0
Mysqlx_bytes_sent_uncompressed_frame......................... 0
Mysqlx_compression_algorithm................................. 
Mysqlx_compression_level..................................... 
Mysqlx_connection_accept_errors.............................. 0
Mysqlx_connection_errors..................................... 0
Mysqlx_connections_accepted.................................. 0
Mysqlx_connections_closed.................................... 0
Mysqlx_connections_rejected.................................. 0
Mysqlx_crud_create_view...................................... 0
Mysqlx_crud_delete........................................... 0
Mysqlx_crud_drop_view........................................ 0
Mysqlx_crud_find............................................. 0
Mysqlx_crud_insert........................................... 0
Mysqlx_crud_modify_view...................................... 0
Mysqlx_crud_update........................................... 0
Mysqlx_cursor_close.......................................... 0
Mysqlx_cursor_fetch.......................................... 0
Mysqlx_cursor_open........................................... 0
Mysqlx_errors_sent........................................... 0
Mysqlx_errors_unknown_message_type........................... 0
Mysqlx_expect_close.......................................... 0
Mysqlx_expect_open........................................... 0
Mysqlx_init_error............................................ 0
Mysqlx_messages_sent......................................... 0
Mysqlx_notice_global_sent.................................... 0
Mysqlx_notice_other_sent..................................... 0
Mysqlx_notice_warning_sent................................... 0
Mysqlx_notified_by_group_replication......................... 0
Mysqlx_port.................................................. 33060
Mysqlx_prep_deallocate....................................... 0
Mysqlx_prep_execute.......................................... 0
Mysqlx_prep_prepare.......................................... 0
Mysqlx_rows_sent............................................. 0
Mysqlx_sessions.............................................. 0
Mysqlx_sessions_accepted..................................... 0
Mysqlx_sessions_closed....................................... 0
Mysqlx_sessions_fatal_error.................................. 0
Mysqlx_sessions_killed....................................... 0
Mysqlx_sessions_rejected..................................... 0
Mysqlx_socket................................................ UNDEFINED
Mysqlx_ssl_accepts........................................... 0
Mysqlx_ssl_active............................................ 
Mysqlx_ssl_cipher............................................ 
Mysqlx_ssl_cipher_list....................................... 
Mysqlx_ssl_ctx_verify_depth.................................. 18446744073709551615
Mysqlx_ssl_ctx_verify_mode................................... 5
Mysqlx_ssl_finished_accepts.................................. 0
Mysqlx_ssl_server_not_after.................................. May 28 09:43:14 2031 GMT
Mysqlx_ssl_server_not_before................................. May 30 09:43:14 2021 GMT
Mysqlx_ssl_verify_depth...................................... 
Mysqlx_ssl_verify_mode....................................... 
Mysqlx_ssl_version........................................... 
Mysqlx_stmt_create_collection................................ 0
Mysqlx_stmt_create_collection_index.......................... 0
Mysqlx_stmt_disable_notices.................................. 0
Mysqlx_stmt_drop_collection.................................. 0
Mysqlx_stmt_drop_collection_index............................ 0
Mysqlx_stmt_enable_notices................................... 0
Mysqlx_stmt_ensure_collection................................ 0
Mysqlx_stmt_execute_mysqlx................................... 0
Mysqlx_stmt_execute_sql...................................... 0
Mysqlx_stmt_execute_xplugin.................................. 0
Mysqlx_stmt_get_collection_options........................... 0
Mysqlx_stmt_kill_client...................................... 0
Mysqlx_stmt_list_clients..................................... 0
Mysqlx_stmt_list_notices..................................... 0
Mysqlx_stmt_list_objects..................................... 0
Mysqlx_stmt_modify_collection_options........................ 0
Mysqlx_stmt_ping............................................. 0
Mysqlx_worker_threads........................................ 2
Mysqlx_worker_threads_active................................. 0
Not_flushed_delayed_rows..................................... 0
Ongoing_anonymous_transaction_count.......................... 0
Open_files................................................... 3
Open_streams................................................. 0
Open_table_definitions....................................... 113
Open_tables.................................................. 730
Opened_files................................................. 3
Opened_table_definitions..................................... 196
Opened_tables................................................ 825
Performance_schema_accounts_lost............................. 0
Performance_schema_cond_classes_lost......................... 0
Performance_schema_cond_instances_lost....................... 0
Performance_schema_digest_lost............................... 0
Performance_schema_file_classes_lost......................... 0
Performance_schema_file_handles_lost......................... 0
Performance_schema_file_instances_lost....................... 0
Performance_schema_hosts_lost................................ 0
Performance_schema_index_stat_lost........................... 0
Performance_schema_locker_lost............................... 0
Performance_schema_memory_classes_lost....................... 0
Performance_schema_metadata_lock_lost........................ 0
Performance_schema_mutex_classes_lost........................ 0
Performance_schema_mutex_instances_lost...................... 0
Performance_schema_nested_statement_lost..................... 0
Performance_schema_prepared_statements_lost.................. 0
Performance_schema_program_lost.............................. 0
Performance_schema_rwlock_classes_lost....................... 0
Performance_schema_rwlock_instances_lost..................... 0
Performance_schema_session_connect_attrs_longest_seen........ 238
Performance_schema_session_connect_attrs_lost................ 0
Performance_schema_socket_classes_lost....................... 0
Performance_schema_socket_instances_lost..................... 0
Performance_schema_stage_classes_lost........................ 0
Performance_schema_statement_classes_lost.................... 0
Performance_schema_table_handles_lost........................ 0
Performance_schema_table_instances_lost...................... 0
Performance_schema_table_lock_stat_lost...................... 0
Performance_schema_thread_classes_lost....................... 0
Performance_schema_thread_instances_lost..................... 0
Performance_schema_users_lost................................ 0
Prepared_stmt_count.......................................... 0
Queries...................................................... 21508
Questions.................................................... 10313
Rsa_public_key............................................... -----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApqwVoScqJgf0tuBfPZeE
ywtgj0ms3P4WH7sdgYuSW3A7rxdJ7lspferXE7VEAaNtQ0jo2akUBxCCIH4u7ri9
Zk830eC0pCAgSqXZenbVwB3ffi5YfsIelND2vEUkpmIuFbsYL+dxcbmqX+qbcSCF
uOb0b/ZKH5Mdok1sGtgjt8N3Mcia9TsiLTrOo5Vp8NXP2odA9e3IMcTI9zg1L1L+
Nor2g9FY+WbXtX+LoERuAwJd7QOOmt5nveMZtK9ZxGc1pGy0kjwTy7HlLe7FZvb1
XuOWnTEQMVBoZcWjml3U5FE56ZWM/GIKx0Ed+vdVOms0hyKHRN/acaRMsbTtNGKC
WwIDAQAB
-----END PUBLIC KEY-----

Secondary_engine_execution_count............................. 0
Select_full_join............................................. 127
Select_full_range_join....................................... 0
Select_range................................................. 0
Select_range_check........................................... 0
Select_scan.................................................. 6681
Slave_open_temp_tables....................................... 0
Slow_launch_threads.......................................... 0
Slow_queries................................................. 1
Sort_merge_passes............................................ 0
Sort_range................................................... 0
Sort_rows.................................................... 6383
Sort_scan.................................................... 487
Ssl_accept_renegotiates...................................... 0
Ssl_accepts.................................................. 88
Ssl_callback_cache_hits...................................... 0
Ssl_cipher................................................... TLS_AES_256_GCM_SHA384
Ssl_cipher_list.............................................. TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-DSS-AES128-SHA256:DHE-DSS-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-DSS-AES128-SHA:DHE-RSA-AES128-SHA:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES256-SHA:CAMELLIA256-SHA:CAMELLIA128-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA
Ssl_client_connects.......................................... 0
Ssl_connect_renegotiates..................................... 0
Ssl_ctx_verify_depth......................................... 4294967295
Ssl_ctx_verify_mode.......................................... 5
Ssl_default_timeout.......................................... 7200
Ssl_finished_accepts......................................... 88
Ssl_finished_connects........................................ 0
Ssl_server_not_after......................................... May 28 09:43:14 2031 GMT
Ssl_server_not_before........................................ May 30 09:43:14 2021 GMT
Ssl_session_cache_hits....................................... 9
Ssl_session_cache_misses..................................... 0
Ssl_session_cache_mode....................................... SERVER
Ssl_session_cache_overflows.................................. 0
Ssl_session_cache_size....................................... 128
Ssl_session_cache_timeouts................................... 0
Ssl_sessions_reused.......................................... 0
Ssl_used_session_cache_entries............................... 0
Ssl_verify_depth............................................. 4294967295
Ssl_verify_mode.............................................. 5
Ssl_version.................................................. TLSv1.3
Table_locks_immediate........................................ 3119
Table_locks_waited........................................... 0
Table_open_cache_hits........................................ 21463
Table_open_cache_misses...................................... 842
Table_open_cache_overflows................................... 0
Tc_log_max_pages_used........................................ 0
Tc_log_page_size............................................. 0
Tc_log_page_waits............................................ 0
Threads_cached............................................... 1
Threads_connected............................................ 4
Threads_created.............................................. 5
Threads_running.............................................. 2
Uptime....................................................... 605114
Uptime_since_flush_status.................................... 605114

GLOBAL VARIABLES:
activate_all_roles_on_login.................................. OFF
admin_address................................................ 
admin_port................................................... 33062
admin_ssl_ca................................................. 
admin_ssl_capath............................................. 
admin_ssl_cert............................................... 
admin_ssl_cipher............................................. 
admin_ssl_crl................................................ 
admin_ssl_crlpath............................................ 
admin_ssl_key................................................ 
admin_tls_ciphersuites....................................... 
admin_tls_version............................................ TLSv1,TLSv1.1,TLSv1.2,TLSv1.3
auto_generate_certs.......................................... ON
auto_increment_increment..................................... 1
auto_increment_offset........................................ 1
autocommit................................................... ON
automatic_sp_privileges...................................... ON
avoid_temporal_upgrade....................................... OFF
back_log..................................................... 80
basedir...................................................... C:\Program Files\MySQL\MySQL Server 8.0\
big_tables................................................... OFF
bind_address................................................. *
binlog_cache_size............................................ 32768
binlog_checksum.............................................. CRC32
binlog_direct_non_transactional_updates...................... OFF
binlog_encryption............................................ OFF
binlog_error_action.......................................... ABORT_SERVER
binlog_expire_logs_seconds................................... 2592000
binlog_format................................................ ROW
binlog_group_commit_sync_delay............................... 0
binlog_group_commit_sync_no_delay_count...................... 0
binlog_gtid_simple_recovery.................................. ON
binlog_max_flush_queue_time.................................. 0
binlog_order_commits......................................... ON
binlog_rotate_encryption_master_key_at_startup............... OFF
binlog_row_event_max_size.................................... 8192
binlog_row_image............................................. FULL
binlog_row_metadata.......................................... MINIMAL
binlog_row_value_options..................................... 
binlog_rows_query_log_events................................. OFF
binlog_stmt_cache_size....................................... 32768
binlog_transaction_compression............................... OFF
binlog_transaction_compression_level_zstd.................... 3
binlog_transaction_dependency_history_size................... 25000
binlog_transaction_dependency_tracking....................... COMMIT_ORDER
block_encryption_mode........................................ aes-128-ecb
bulk_insert_buffer_size...................................... 8388608
caching_sha2_password_auto_generate_rsa_keys................. ON
caching_sha2_password_digest_rounds.......................... 5000
caching_sha2_password_private_key_path....................... private_key.pem
caching_sha2_password_public_key_path........................ public_key.pem
character_set_client......................................... utf8mb4
character_set_connection..................................... utf8mb4
character_set_database....................................... utf8mb4
character_set_filesystem..................................... binary
character_set_results........................................ utf8mb4
character_set_server......................................... utf8mb4
character_set_system......................................... utf8mb3
character_sets_dir........................................... C:\Program Files\MySQL\MySQL Server 8.0\share\charsets\
check_proxy_users............................................ OFF
collation_connection......................................... utf8mb4_0900_ai_ci
collation_database........................................... utf8mb4_0900_ai_ci
collation_server............................................. utf8mb4_0900_ai_ci
completion_type.............................................. NO_CHAIN
concurrent_insert............................................ AUTO
connect_timeout.............................................. 10
core_file.................................................... OFF
create_admin_listener_thread................................. OFF
cte_max_recursion_depth...................................... 1000
datadir...................................................... C:\ProgramData\MySQL\MySQL Server 8.0\Data\
default_authentication_plugin................................ mysql_native_password
default_collation_for_utf8mb4................................ utf8mb4_0900_ai_ci
default_password_lifetime.................................... 0
default_storage_engine....................................... InnoDB
default_table_encryption..................................... OFF
default_tmp_storage_engine................................... InnoDB
default_week_format.......................................... 0
delay_key_write.............................................. ON
delayed_insert_limit......................................... 100
delayed_insert_timeout....................................... 300
delayed_queue_size........................................... 1000
disabled_storage_engines..................................... 
disconnect_on_expired_password............................... ON
div_precision_increment...................................... 4
end_markers_in_json.......................................... OFF
enforce_gtid_consistency..................................... OFF
eq_range_index_dive_limit.................................... 200
event_scheduler.............................................. ON
expire_logs_days............................................. 0
explicit_defaults_for_timestamp.............................. ON
flush........................................................ OFF
flush_time................................................... 0
foreign_key_checks........................................... ON
ft_boolean_syntax............................................ + -><()~*:""&|
ft_max_word_len.............................................. 84
ft_min_word_len.............................................. 4
ft_query_expansion_limit..................................... 20
ft_stopword_file............................................. (built-in)
general_log.................................................. OFF
general_log_file............................................. LENOVO-PC.log
generated_random_password_length............................. 20
group_concat_max_len......................................... 1024
group_replication_consistency................................ EVENTUAL
gtid_executed................................................ 
gtid_executed_compression_period............................. 0
gtid_mode.................................................... OFF
gtid_owned................................................... 
gtid_purged.................................................. 
have_compress................................................ YES
have_dynamic_loading......................................... YES
have_geometry................................................ YES
have_openssl................................................. YES
have_profiling............................................... YES
have_query_cache............................................. NO
have_rtree_keys.............................................. YES
have_ssl..................................................... YES
have_statement_timeout....................................... YES
have_symlink................................................. DISABLED
histogram_generation_max_mem_size............................ 20000000
host_cache_size.............................................. 279
hostname..................................................... Lenovo-PC
information_schema_stats_expiry.............................. 86400
init_connect................................................. 
init_file.................................................... 
init_slave................................................... 
innodb_adaptive_flushing..................................... ON
innodb_adaptive_flushing_lwm................................. 10
innodb_adaptive_hash_index................................... ON
innodb_adaptive_hash_index_parts............................. 8
innodb_adaptive_max_sleep_delay.............................. 150000
innodb_api_bk_commit_interval................................ 5
innodb_api_disable_rowlock................................... OFF
innodb_api_enable_binlog..................................... OFF
innodb_api_enable_mdl........................................ OFF
innodb_api_trx_level......................................... 0
innodb_autoextend_increment.................................. 64
innodb_autoinc_lock_mode..................................... 2
innodb_buffer_pool_chunk_size................................ 8388608
innodb_buffer_pool_dump_at_shutdown.......................... ON
innodb_buffer_pool_dump_now.................................. OFF
innodb_buffer_pool_dump_pct.................................. 25
innodb_buffer_pool_filename.................................. ib_buffer_pool
innodb_buffer_pool_in_core_file.............................. ON
innodb_buffer_pool_instances................................. 1
innodb_buffer_pool_load_abort................................ OFF
innodb_buffer_pool_load_at_startup........................... ON
innodb_buffer_pool_load_now.................................. OFF
innodb_buffer_pool_size...................................... 8388608
innodb_change_buffer_max_size................................ 25
innodb_change_buffering...................................... all
innodb_checksum_algorithm.................................... crc32
innodb_cmp_per_index_enabled................................. OFF
innodb_commit_concurrency.................................... 0
innodb_compression_failure_threshold_pct..................... 5
innodb_compression_level..................................... 6
innodb_compression_pad_pct_max............................... 50
innodb_concurrency_tickets................................... 5000
innodb_data_file_path........................................ ibdata1:12M:autoextend
innodb_data_home_dir......................................... 
innodb_deadlock_detect....................................... ON
innodb_dedicated_server...................................... OFF
innodb_default_row_format.................................... dynamic
innodb_directories........................................... 
innodb_disable_sort_file_cache............................... OFF
innodb_doublewrite........................................... ON
innodb_doublewrite_batch_size................................ 0
innodb_doublewrite_dir....................................... 
innodb_doublewrite_files..................................... 2
innodb_doublewrite_pages..................................... 4
innodb_extend_and_initialize................................. ON
innodb_fast_shutdown......................................... 1
innodb_file_per_table........................................ ON
innodb_fill_factor........................................... 100
innodb_flush_log_at_timeout.................................. 1
innodb_flush_log_at_trx_commit............................... 1
innodb_flush_method.......................................... unbuffered
innodb_flush_neighbors....................................... 0
innodb_flush_sync............................................ ON
innodb_flushing_avg_loops.................................... 30
innodb_force_load_corrupted.................................. OFF
innodb_force_recovery........................................ 0
innodb_fsync_threshold....................................... 0
innodb_ft_aux_table.......................................... 
innodb_ft_cache_size......................................... 8000000
innodb_ft_enable_diag_print.................................. OFF
innodb_ft_enable_stopword.................................... ON
innodb_ft_max_token_size..................................... 84
innodb_ft_min_token_size..................................... 3
innodb_ft_num_word_optimize.................................. 2000
innodb_ft_result_cache_limit................................. 2000000000
innodb_ft_server_stopword_table.............................. 
innodb_ft_sort_pll_degree.................................... 2
innodb_ft_total_cache_size................................... 640000000
innodb_ft_user_stopword_table................................ 
innodb_idle_flush_pct........................................ 100
innodb_io_capacity........................................... 200
innodb_io_capacity_max....................................... 2000
innodb_lock_wait_timeout..................................... 50
innodb_log_buffer_size....................................... 1048576
innodb_log_checksums......................................... ON
innodb_log_compressed_pages.................................. ON
innodb_log_file_size......................................... 50331648
innodb_log_files_in_group.................................... 2
innodb_log_group_home_dir.................................... .\
innodb_log_spin_cpu_abs_lwm.................................. 80
innodb_log_spin_cpu_pct_hwm.................................. 50
innodb_log_wait_for_flush_spin_hwm........................... 400
innodb_log_write_ahead_size.................................. 8192
innodb_log_writer_threads.................................... ON
innodb_lru_scan_depth........................................ 1024
innodb_max_dirty_pages_pct................................... 90.000000
innodb_max_dirty_pages_pct_lwm............................... 10.000000
innodb_max_purge_lag......................................... 0
innodb_max_purge_lag_delay................................... 0
innodb_max_undo_log_size..................................... 1073741824
innodb_monitor_disable....................................... 
innodb_monitor_enable........................................ 
innodb_monitor_reset......................................... 
innodb_monitor_reset_all..................................... 
innodb_old_blocks_pct........................................ 37
innodb_old_blocks_time....................................... 1000
innodb_online_alter_log_max_size............................. 134217728
innodb_open_files............................................ 300
innodb_optimize_fulltext_only................................ OFF
innodb_page_cleaners......................................... 1
innodb_page_size............................................. 16384
innodb_parallel_read_threads................................. 4
innodb_print_all_deadlocks................................... OFF
innodb_print_ddl_logs........................................ OFF
innodb_purge_batch_size...................................... 300
innodb_purge_rseg_truncate_frequency......................... 128
innodb_purge_threads......................................... 4
innodb_random_read_ahead..................................... OFF
innodb_read_ahead_threshold.................................. 56
innodb_read_io_threads....................................... 4
innodb_read_only............................................. OFF
innodb_redo_log_archive_dirs................................. 
innodb_redo_log_encrypt...................................... OFF
innodb_replication_delay..................................... 0
innodb_rollback_on_timeout................................... OFF
innodb_rollback_segments..................................... 128
innodb_sort_buffer_size...................................... 1048576
innodb_spin_wait_delay....................................... 6
innodb_spin_wait_pause_multiplier............................ 50
innodb_stats_auto_recalc..................................... ON
innodb_stats_include_delete_marked........................... OFF
innodb_stats_method.......................................... nulls_equal
innodb_stats_on_metadata..................................... OFF
innodb_stats_persistent...................................... ON
innodb_stats_persistent_sample_pages......................... 20
innodb_stats_transient_sample_pages.......................... 8
innodb_status_output......................................... OFF
innodb_status_output_locks................................... OFF
innodb_strict_mode........................................... ON
innodb_sync_array_size....................................... 1
innodb_sync_spin_loops....................................... 30
innodb_table_locks........................................... ON
innodb_temp_data_file_path................................... ibtmp1:12M:autoextend
innodb_temp_tablespaces_dir.................................. .\#innodb_temp\
innodb_thread_concurrency.................................... 9
innodb_thread_sleep_delay.................................... 0
innodb_tmpdir................................................ 
innodb_undo_directory........................................ .\
innodb_undo_log_encrypt...................................... OFF
innodb_undo_log_truncate..................................... ON
innodb_undo_tablespaces...................................... 2
innodb_use_native_aio........................................ ON
innodb_validate_tablespace_paths............................. ON
innodb_version............................................... 8.0.24
innodb_write_io_threads...................................... 4
interactive_timeout.......................................... 28800
internal_tmp_mem_storage_engine.............................. TempTable
join_buffer_size............................................. 262144
keep_files_on_create......................................... OFF
key_buffer_size.............................................. 8388608
key_cache_age_threshold...................................... 300
key_cache_block_size......................................... 1024
key_cache_division_limit..................................... 100
keyring_operations........................................... ON
large_files_support.......................................... ON
large_page_size.............................................. 0
large_pages.................................................. OFF
lc_messages.................................................. en_US
lc_messages_dir.............................................. C:\Program Files\MySQL\MySQL Server 8.0\share\
lc_time_names................................................ en_US
license...................................................... GPL
local_infile................................................. OFF
lock_wait_timeout............................................ 31536000
log_bin...................................................... ON
log_bin_basename............................................. C:\ProgramData\MySQL\MySQL Server 8.0\Data\LENOVO-PC-bin
log_bin_index................................................ C:\ProgramData\MySQL\MySQL Server 8.0\Data\LENOVO-PC-bin.index
log_bin_trust_function_creators.............................. OFF
log_bin_use_v1_row_events.................................... OFF
log_error.................................................... .\LENOVO-PC.err
log_error_services........................................... log_filter_internal; log_sink_internal
log_error_suppression_list................................... 
log_error_verbosity.......................................... 2
log_output................................................... FILE
log_queries_not_using_indexes................................ OFF
log_raw...................................................... OFF
log_slave_updates............................................ ON
log_slow_admin_statements.................................... OFF
log_slow_extra............................................... OFF
log_slow_slave_statements.................................... OFF
log_statements_unsafe_for_binlog............................. ON
log_throttle_queries_not_using_indexes....................... 0
log_timestamps............................................... UTC
long_query_time.............................................. 10.000000
low_priority_updates......................................... OFF
lower_case_file_system....................................... ON
lower_case_table_names....................................... 1
mandatory_roles.............................................. 
master_info_repository....................................... TABLE
master_verify_checksum....................................... OFF
max_allowed_packet........................................... 4194304
max_binlog_cache_size........................................ 18446744073709547520
max_binlog_size.............................................. 1073741824
max_binlog_stmt_cache_size................................... 18446744073709547520
max_connect_errors........................................... 100
max_connections.............................................. 151
max_delayed_threads.......................................... 20
max_digest_length............................................ 1024
max_error_count.............................................. 1024
max_execution_time........................................... 0
max_heap_table_size.......................................... 16777216
max_insert_delayed_threads................................... 20
max_join_size................................................ 18446744073709551615
max_length_for_sort_data..................................... 4096
max_points_in_geometry....................................... 65536
max_prepared_stmt_count...................................... 16382
max_relay_log_size........................................... 0
max_seeks_for_key............................................ 4294967295
max_sort_length.............................................. 1024
max_sp_recursion_depth....................................... 0
max_user_connections......................................... 0
max_write_lock_count......................................... 4294967295
min_examined_row_limit....................................... 0
myisam_data_pointer_size..................................... 6
myisam_max_sort_file_size.................................... 107374182400
myisam_mmap_size............................................. 18446744073709551615
myisam_recover_options....................................... OFF
myisam_repair_threads........................................ 1
myisam_sort_buffer_size...................................... 79691776
myisam_stats_method.......................................... nulls_unequal
myisam_use_mmap.............................................. OFF
mysql_native_password_proxy_users............................ OFF
mysqlx_bind_address.......................................... *
mysqlx_compression_algorithms................................ DEFLATE_STREAM,LZ4_MESSAGE,ZSTD_STREAM
mysqlx_connect_timeout....................................... 30
mysqlx_deflate_default_compression_level..................... 3
mysqlx_deflate_max_client_compression_level.................. 5
mysqlx_document_id_unique_prefix............................. 0
mysqlx_enable_hello_notice................................... ON
mysqlx_idle_worker_thread_timeout............................ 60
mysqlx_interactive_timeout................................... 28800
mysqlx_lz4_default_compression_level......................... 2
mysqlx_lz4_max_client_compression_level...................... 8
mysqlx_max_allowed_packet.................................... 67108864
mysqlx_max_connections....................................... 100
mysqlx_min_worker_threads.................................... 2
mysqlx_port.................................................. 33060
mysqlx_port_open_timeout..................................... 0
mysqlx_read_timeout.......................................... 30
mysqlx_socket................................................ /tmp/mysqlx.sock
mysqlx_ssl_ca................................................ 
mysqlx_ssl_capath............................................ 
mysqlx_ssl_cert.............................................. 
mysqlx_ssl_cipher............................................ 
mysqlx_ssl_crl............................................... 
mysqlx_ssl_crlpath........................................... 
mysqlx_ssl_key............................................... 
mysqlx_wait_timeout.......................................... 28800
mysqlx_write_timeout......................................... 60
mysqlx_zstd_default_compression_level........................ 3
mysqlx_zstd_max_client_compression_level..................... 11
named_pipe................................................... OFF
named_pipe_full_access_group................................. 
net_buffer_length............................................ 16384
net_read_timeout............................................. 30
net_retry_count.............................................. 10
net_write_timeout............................................ 60
new.......................................................... OFF
ngram_token_size............................................. 2
offline_mode................................................. ON
old.......................................................... OFF
old_alter_table.............................................. OFF
open_files_limit............................................. 6209
optimizer_prune_level........................................ 1
optimizer_search_depth....................................... 62
optimizer_switch............................................. index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,engine_condition_pushdown=on,index_condition_pushdown=on,mrr=on,mrr_cost_based=on,block_nested_loop=on,batched_key_access=off,materialization=on,semijoin=on,loosescan=on,firstmatch=on,duplicateweedout=on,subquery_materialization_cost_based=on,use_index_extensions=on,condition_fanout_filter=on,derived_merge=on,use_invisible_indexes=off,skip_scan=on,hash_join=on,subquery_to_derived=off,prefer_ordering_index=on,hypergraph_optimizer=off,derived_condition_pushdown=on
optimizer_trace.............................................. enabled=off,one_line=off
optimizer_trace_features..................................... greedy_search=on,range_optimizer=on,dynamic_range=on,repeated_subselect=on
optimizer_trace_limit........................................ 1
optimizer_trace_max_mem_size................................. 1048576
optimizer_trace_offset....................................... -1
parser_max_mem_size.......................................... 18446744073709551615
partial_revokes.............................................. OFF
password_history............................................. 0
password_require_current..................................... OFF
password_reuse_interval...................................... 0
performance_schema........................................... ON
performance_schema_accounts_size............................. -1
performance_schema_digests_size.............................. 10000
performance_schema_error_size................................ 4890
performance_schema_events_stages_history_long_size........... 10000
performance_schema_events_stages_history_size................ 10
performance_schema_events_statements_history_long_size....... 10000
performance_schema_events_statements_history_size............ 10
performance_schema_events_transactions_history_long_size..... 10000
performance_schema_events_transactions_history_size.......... 10
performance_schema_events_waits_history_long_size............ 10000
performance_schema_events_waits_history_size................. 10
performance_schema_hosts_size................................ -1
performance_schema_max_cond_classes.......................... 100
performance_schema_max_cond_instances........................ -1
performance_schema_max_digest_length......................... 1024
performance_schema_max_digest_sample_age..................... 60
performance_schema_max_file_classes.......................... 80
performance_schema_max_file_handles.......................... 32768
performance_schema_max_file_instances........................ -1
performance_schema_max_index_stat............................ -1
performance_schema_max_memory_classes........................ 450
performance_schema_max_metadata_locks........................ -1
performance_schema_max_mutex_classes......................... 300
performance_schema_max_mutex_instances....................... -1
performance_schema_max_prepared_statements_instances......... -1
performance_schema_max_program_instances..................... -1
performance_schema_max_rwlock_classes........................ 60
performance_schema_max_rwlock_instances...................... -1
performance_schema_max_socket_classes........................ 10
performance_schema_max_socket_instances...................... -1
performance_schema_max_sql_text_length....................... 1024
performance_schema_max_stage_classes......................... 175
performance_schema_max_statement_classes..................... 218
performance_schema_max_statement_stack....................... 10
performance_schema_max_table_handles......................... -1
performance_schema_max_table_instances....................... -1
performance_schema_max_table_lock_stat....................... -1
performance_schema_max_thread_classes........................ 100
performance_schema_max_thread_instances...................... -1
performance_schema_session_connect_attrs_size................ 512
performance_schema_setup_actors_size......................... -1
performance_schema_setup_objects_size........................ -1
performance_schema_show_processlist.......................... OFF
performance_schema_users_size................................ -1
persist_only_admin_x509_subject.............................. 
persisted_globals_load....................................... ON
pid_file..................................................... C:\ProgramData\MySQL\MySQL Server 8.0\Data\Lenovo-PC.pid
plugin_dir................................................... C:\Program Files\MySQL\MySQL Server 8.0\lib\plugin\
port......................................................... 3306
preload_buffer_size.......................................... 32768
print_identified_with_as_hex................................. OFF
profiling.................................................... OFF
profiling_history_size....................................... 15
protocol_compression_algorithms.............................. zlib,zstd,uncompressed
protocol_version............................................. 10
query_alloc_block_size....................................... 8192
query_prealloc_size.......................................... 8192
range_alloc_block_size....................................... 4096
range_optimizer_max_mem_size................................. 8388608
rbr_exec_mode................................................ STRICT
read_buffer_size............................................. 65536
read_only.................................................... OFF
read_rnd_buffer_size......................................... 262144
regexp_stack_limit........................................... 8000000
regexp_time_limit............................................ 32
relay_log.................................................... Lenovo-PC-relay-bin
relay_log_basename........................................... C:\ProgramData\MySQL\MySQL Server 8.0\Data\Lenovo-PC-relay-bin
relay_log_index.............................................. C:\ProgramData\MySQL\MySQL Server 8.0\Data\Lenovo-PC-relay-bin.index
relay_log_info_file.......................................... relay-log.info
relay_log_info_repository.................................... TABLE
relay_log_purge.............................................. ON
relay_log_recovery........................................... OFF
relay_log_space_limit........................................ 0
replication_optimize_for_static_plugin_config................ OFF
replication_sender_observe_commit_only....................... OFF
report_host.................................................. 
report_password.............................................. 
report_port.................................................. 3306
report_user.................................................. 
require_secure_transport..................................... OFF
rpl_read_size................................................ 8192
rpl_stop_slave_timeout....................................... 31536000
schema_definition_cache...................................... 256
secondary_engine_cost_threshold.............................. 100000.000000
secure_file_priv............................................. C:\ProgramData\MySQL\MySQL Server 8.0\Uploads\
select_into_buffer_size...................................... 131072
select_into_disk_sync........................................ OFF
select_into_disk_sync_delay.................................. 0
server_id.................................................... 1
server_id_bits............................................... 32
server_uuid.................................................. 72350cc3-c12b-11eb-a8e4-8056f2f88f34
session_track_gtids.......................................... OFF
session_track_schema......................................... ON
session_track_state_change................................... OFF
session_track_system_variables............................... time_zone,autocommit,character_set_client,character_set_results,character_set_connection
session_track_transaction_info............................... OFF
sha256_password_auto_generate_rsa_keys....................... ON
sha256_password_private_key_path............................. private_key.pem
sha256_password_proxy_users.................................. OFF
sha256_password_public_key_path.............................. public_key.pem
shared_memory................................................ OFF
shared_memory_base_name...................................... MYSQL
show_create_table_verbosity.................................. OFF
show_old_temporals........................................... OFF
skip_external_locking........................................ ON
skip_name_resolve............................................ OFF
skip_networking.............................................. OFF
skip_show_database........................................... OFF
skip_slave_start............................................. OFF
slave_allow_batching......................................... OFF
slave_checkpoint_group....................................... 512
slave_checkpoint_period...................................... 300
slave_compressed_protocol.................................... OFF
slave_exec_mode.............................................. STRICT
slave_load_tmpdir............................................ C:\Windows\SERVIC~2\NETWOR~1\AppData\Local\Temp
slave_max_allowed_packet..................................... 1073741824
slave_net_timeout............................................ 60
slave_parallel_type.......................................... DATABASE
slave_parallel_workers....................................... 0
slave_pending_jobs_size_max.................................. 134217728
slave_preserve_commit_order.................................. OFF
slave_rows_search_algorithms................................. INDEX_SCAN,HASH_SCAN
slave_skip_errors............................................ OFF
slave_sql_verify_checksum.................................... ON
slave_transaction_retries.................................... 10
slave_type_conversions....................................... 
slow_launch_time............................................. 2
slow_query_log............................................... ON
slow_query_log_file.......................................... LENOVO-PC-slow.log
socket....................................................... MySQL
sort_buffer_size............................................. 262144
sql_auto_is_null............................................. OFF
sql_big_selects.............................................. ON
sql_buffer_result............................................ OFF
sql_log_off.................................................. OFF
sql_mode..................................................... STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
sql_notes.................................................... ON
sql_quote_show_create........................................ ON
sql_require_primary_key...................................... OFF
sql_safe_updates............................................. OFF
sql_select_limit............................................. 18446744073709551615
sql_slave_skip_counter....................................... 0
sql_warnings................................................. OFF
ssl_ca....................................................... ca.pem
ssl_capath................................................... 
ssl_cert..................................................... server-cert.pem
ssl_cipher................................................... 
ssl_crl...................................................... 
ssl_crlpath.................................................. 
ssl_fips_mode................................................ OFF
ssl_key...................................................... server-key.pem
stored_program_cache......................................... 256
stored_program_definition_cache.............................. 256
super_read_only.............................................. OFF
sync_binlog.................................................. 1
sync_master_info............................................. 10000
sync_relay_log............................................... 10000
sync_relay_log_info.......................................... 10000
system_time_zone............................................. W. Central Africa Standard Ti
table_definition_cache....................................... 1400
table_encryption_privilege_check............................. OFF
table_open_cache............................................. 2000
table_open_cache_instances................................... 16
tablespace_definition_cache.................................. 256
temptable_max_mmap........................................... 1073741824
temptable_max_ram............................................ 1073741824
temptable_use_mmap........................................... ON
thread_cache_size............................................ 10
thread_handling.............................................. one-thread-per-connection
thread_stack................................................. 286720
time_zone.................................................... SYSTEM
tls_ciphersuites............................................. 
tls_version.................................................. TLSv1,TLSv1.1,TLSv1.2,TLSv1.3
tmp_table_size............................................... 45088768
tmpdir....................................................... C:\Windows\SERVIC~2\NETWOR~1\AppData\Local\Temp
transaction_alloc_block_size................................. 8192
transaction_isolation........................................ REPEATABLE-READ
transaction_prealloc_size.................................... 4096
transaction_read_only........................................ OFF
transaction_write_set_extraction............................. XXHASH64
unique_checks................................................ ON
updatable_views_with_limit................................... YES
version...................................................... 8.0.24
version_comment.............................................. MySQL Community Server - GPL
version_compile_machine...................................... x86_64
version_compile_os........................................... Win64
version_compile_zlib......................................... 1.2.11
wait_timeout................................................. 28800
windowing_use_high_precision................................. ON